/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    GoogleClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleRedirectUri: {
      type: "sst.sst.Secret";
      value: string;
    };
    MyApi: {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
    MyUserPool: {
      id: string;
      type: "sst.aws.CognitoUserPool";
    };
    MyUserPoolClient: {
      id: string;
      secret: string;
      type: "sst.aws.CognitoUserPoolClient";
    };
    MyWebsite: {
      type: "sst.aws.React";
      url: string;
    };
    UsersTable: {
      name: string;
      type: "sst.aws.Dynamo";
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
